name: CI
 
on:
    push:
        branches:
            - main # 这里只配置了main分支，所以只有推送main分支才会触发以下任务
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "14.x"
            - run: node -v
            - run: npm install
            - run: npm run build
            - name: Vite Github Pages Deployer
              uses: skywarth/vite-github-pages-deployer@v1.1.0
            #- name: Deploy # 部署
            #  uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  ACCESS_TOKEN: ${{ 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 }} # 也就是我们刚才生成的 secret
                  branch: gh-pages # 部署后提交到那个分支
                  folder: dist # 这里填打包好的目录名称